### ISSUE TITLE
Unicode characters when hashing password

### ISSUE THREAD

**Issue by brielov** [emilbayes/secure-password#14]
Hi, I don't really know if this is the expected behavior or not, but when I hash a password the result includes a bunch of unicode characters, like so:

`$argon2id$v=19$m=65536,t=2,p=1$aG/+dVRNEcHrdTHLlGTdVg$85tZ6DCyYvZNDudIrLY8kqEBVoRQruSJItI/HR4dxX4\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000`

Is this how it works or am I doing something wrong?

**Comment by emilbayes** [comment]
Hi @brielov,

That is correct! :) Those are NUL bytes and is simply because the serialised buffer is reserving space for future use See https://github.com/emilbayes/secure-password/blob/d7429ac8623bd2b17a2cc739b0ff7908f2aef9f0/index.js#L49-L52

There has been a bunch of bug reports where people's database drivers stipped them out, so the hash you'd verify from the database wouldn't be as long as required. See #10. I'm contemplating whether I should simply pad up the buffer in that case, but I have not done so as I want there to be as little magic as possible
