### ISSUE TITLE
Client-size hash implementation

### ISSUE THREAD

**Issue by Extarys** [emilbayes/secure-password#16]
Edit: client-side* sorry for the typo

Would it be possible to make the hash function works on the client side with libsodium.js or something&

I'd like the server to send the salt and the client to compute the password before sending it back

Thanks!

PS I looked at many argon2 implementation in Node and this one is by far my favorite!

**Comment by emilbayes** [comment]
Hi!

You have to consider why you would want to do this and the security implications. I guess it would a fair point that you want to distribute the computation to the client to alleviate your servers.

However, if it is because you think that it is unsafe to handle plaintext passwords you have to consider that a eavesdropper gains as much from intercepting the client-side hash as he does from intercepting the plaintext, regarding authentication towards your application. It does add some security in that the eavesdropper still would have to try and crack the password from the (salt, hash) pair, if they wanted to learn the plaintext.

Maybe you want to look at protocols such as [SRP](http://srp.stanford.edu/) or SPAKE2, which use Zero-Knowledge proofs to show that a user knows a given password, without an eavesdropper learning anything in the process about the password and the server only holding a verifier.

**Comment by Extarys** [comment]
Thanks!
I read something on libsodium (I don't remember the link) that people may consider hashing on client side with libsodium.js but I'm always scared to do so. Thanks for your links I'll read about it ;)
